app:
  debug: true
  version: 0.0.1
  environment: "development"
http:
  port: 3100
  idleTimeout: "60s"
  readTimeout: "5s"
  writeTimeout: "10s"
database:
  maxOpenConnections: 25
  maxIdleConnections: 25
  maxIdleTime: "15m"
authentication:
  accessTokenExpiresIn: "5m"
  refreshTokenExpiresIn: "72h"